### ISSUE TITLE
"format": "iri" ?

### ISSUE THREAD

**Issue by nmanaud** [jjrom/healthcheckr#1]
Ca corresponds a quoi "format": "iri" dans le schema:
https://github.com/jjrom/healthcheckr/blob/720a5ef2cf7848bff1278336ceb97c349867f305/app/schemas/service.json#L43

**Comment by jjrom** [comment]
[Internationalized Resource Identifier](https://fr.wikipedia.org/wiki/Internationalized_Resource_Identifier)
